image: docker:19

services:
  - docker:dind

stages:
  - build

app:
  stage: build
  only:
    - branches
    - merge_requests
    - tags
  script:
    - docker build .
  after_script:
    - CID=$(docker create $(docker images --format='{{.ID}}' | head -1))
    - docker cp ${CID}:/srv/artifacts .
  artifacts:
    reports:
      junit: artifacts/*.xml
