version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependencies
    restart: unless-stopped
    tty: true
    volumes:
      - vendor:/srv/vendor
      - ./composer.json:/srv/composer.json
      - ./composer.lock:/srv/composer.lock
      - .:/srv
    env_file: .env
    ports:
      - ${SERVER_PORT:-8094}:8080
    container_name: ${SERVICE_PREFIX}_app
networks:
  default:
    driver: bridge
volumes:
  vendor:
