version: '3'

silent: true

dotenv: ['.env', '.env.example']

tasks:
  default:
    cmds:
      - task --list
  start:
    desc: Start the local application environment
    cmds:
      - task: up
      - echo "Launched application at http://localhost:$APP_PORT"
  suspend:
    desc: Suspend the local application environment to maintain state for later
    cmds:
      - docker compose down
  stop:
    desc: Stop the local application environment and clean all state
    cmds:
      - docker compose down -v --rmi all --remove-orphans
  logs:
    desc: Stream local environment container output
    cmds:
      - docker compose logs -f
  shell:
    desc: Launch interactive shell for application container
    vars:
      SERVICE: '{{default "app" .SERVICE}}'
    cmds:
      - docker compose exec {{.SERVICE}} sh
  up:
    cmds:
      - docker compose up -d
