name: Build Application Image

on:
  push:
    branches:
      - "**"

env:
  IMAGE: "ghcr.io/${{ github.repository }}"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Generate branch Docker Image attributes
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: "${{ env.IMAGE }}"
          tags: |
            type=ref,event=branch
            type=sha
      - name: Build Docker Image
        id: build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
      - name: Save Docker Image archive to local filesystem
        run: "docker save --output app.tar ${{ env.IMAGE }}"
      - name: Upload application's Docker Image as pipeline artifact
        uses: actions/upload-artifact@v2
        with:
          path: app.tar
          name: app.tar
      - name: "Re-run failed build to `test` stage"
        if: failure()
        uses: docker/build-push-action@v2
        with:
          target: test
          load: true
          tags: "${{ steps.meta.outputs.tags }}"
      - name: Extract test reports from Docker Image
        if: always()
        uses: shrink/actions-docker-extract@v1
        id: reports
        with:
          image: "${{ env.IMAGE }}:${{ steps.meta.outputs.version }}"
          path: /srv/reports/.
      - name: Upload test report(s) as pipeline artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: "${{ steps.reports.outputs.destination }}"
          name: test-reports
