name: Build Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test Presence of GHCR_PAT
      if: ${{ ! secrets.GHCR_PAT }}
      run: |
        echo "::warning file=README.md,line=41,col=0::GHCR_PAT has not been set"
        exit 0
    - uses: actions/checkout@v2
    - name: Build & Publish If Tagged
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
        registry: ghcr.io
        repository: ${{ github.repository }}
        tag_with_ref: true
        add_git_labels: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
    - name: Get Latest Image
      id: latest
      uses: shrink/actions-docker-latest-image@v1
      with:
        repository: ghcr.io/${{ github.repository }}
    - uses: shrink/actions-docker-extract@v1
      id: artifacts
      with:
        image: ${{ steps.latest.outputs.image }}
        path: /srv/artifacts/.
    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.artifacts.outputs.destination }}
        name: 'test-artifacts'
