name: Build Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Publish If Tagged
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
        registry: ghcr.io
        repository: ${{ github.repository }}
        tag_with_ref: true
        add_git_labels: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
    - name: Extract Artifacts
      run: |
        IMAGE=$(docker images --format='{{.ID}}' | head -1)
        CONTAINER=$(docker create ${IMAGE})
        docker cp ${CONTAINER}:/srv/artifacts .
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 'build-artifacts'
        path: artifacts
