name: Build Application

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx
    - name: Ensure new image digest for final layer due to GitHub bug
      run: echo "ADD https://worldtimeapi.org/api/ip.txt cachebuster" >> Dockerfile
    - id: push
      run: |
        echo ::set-output name=sha::sha-${GITHUB_SHA:0:7}
        echo ::set-output name=at::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - name: Build Image
      uses: docker/build-push-action@v2
      with:
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ steps.push.outputs.sha }}
        labels: |
          org.opencontainers.image.title=${{ github.repository }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.html_url }}
          org.opencontainers.image.created=${{ steps.push.outputs.at }}
          org.opencontainers.image.revision=${{ steps.push.outputs.sha }}
    - name: On failure rebuild to test stage for artifact extraction
      if: ${{ failure() }}
      uses: docker/build-push-action@v2
      with:
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        load: true
        tags: ghcr.io/${{ github.repository }}:${{ steps.push.outputs.sha }}
    - uses: shrink/actions-docker-extract@v1
      if: ${{ always() }}
      id: artifacts
      with:
        image: ghcr.io/${{ github.repository }}:${{ steps.push.outputs.sha }}
        path: /srv/artifacts/.
    - name: Upload Test Artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.artifacts.outputs.destination }}
        name: 'test-artifacts'
