name: Build Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build --tag ${{ github.sha }} .
    - name: Extract Artifacts
      run: |
        IMAGE=$(docker images --format='{{.ID}}' | head -1)
        CONTAINER=$(docker create ${IMAGE})
        docker cp ${CONTAINER}:/srv/artifacts .
        ls -a
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 'artifacts'
        path: artifacts
