name: Tag Application Build

on:
  push:
    tags:
      - "**"

jobs:
  add-version-tag:
    runs-on: ubuntu-latest
    steps:
      - id: short
        uses: benjlevesque/short-sha@v1.2
      - id: version
        uses: battila7/get-version-action@v2
      - name: Add version tag to commit build
        uses: shrink/actions-docker-registry-tag@v1
        with:
          registry: ghcr.io
          token: "${{ secrets.GHCR_PAT }}"
          repository: "${{ github.repository }}"
          target: "sha-${{ steps.short.outputs.sha }}"
          tags: "${{ steps.version.outputs.version }}"
